name: Continuous Integration and Deployment

on:
  push:
    branches: "main"

jobs:
  laravel_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Clear Config and Cache
        run: |
          php artisan config:clear
          php artisan route:clear
          php artisan key:generate
      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/home/waseekxy/mightyolugrocery.wasesupportservices.co.uk"