name: Continuous Integration and Deployment

on:
  push:
    branches: "main"

jobs:
  laravel_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build assets
        run: npm install && npm run build
      # - name: Copy .env
      #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Clear Config and Cache
        run: |
          php artisan storage:link
          php artisan key:generate
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          php artisan config:clear
          php artisan optimize:clear
      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.LARAVEL_SITE_SERVER }}
          username: ${{ secrets.LARAVEL_SITE_USER }}
          password: ${{ secrets.LARAVEL_SITE_PASS }}
          server-dir: /
          protocol: ftps
          port: 21
          timeout: 60000
