name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2 
    - name: Build assets
      run: npm install && npm run build

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.2' # Adjust to match the PHP version used by your Laravel project
          tools: 'composer'

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
    - name: List current directory
      run: ls -la
        
    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 21098  # adjust if your SFTP uses a different port
        source: "*" 
        target: "/home/waseekxy/unifood.wasesupportservices.co.uk/" 