name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.LARAVEL_SITE_SERVER}}
        username: ${{ secrets.LARAVEL_SITE_USER}}
        password: ${{ secrets.LARAVEL_SITE_PASS}}
        port: 21 
        log-level: verbose

    - name: ssh key passphrase
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASSWORD }}
        timeout: 120s  # Increase connection timeout
        command_timeout: 20m  # Increase command execution timeout
        script: |
          whoami
          ls -al
          cd unifood.wasesupportservices.co.uk
          composer install --ignore-platform-reqs
          php artisan storage:link
          php artisan config:cache
          php artisan config:clear
          php artisan view:clear
          php artisan cache:clear
          php artisan optimize
          php artisan migrate --force
